### ISSUE TITLE
container not running

### ISSUE THREAD

**Issue by DanielRuf** [proophboard/php-cody-tutorial#1]
setup.sh ends with the following output:

![grafik](https://user-images.githubusercontent.com/827205/227547501-dc0f529f-34d3-4e65-9661-9bb1b669893f.png)

So there is some non-zero exitcode. `docker ps` shows no running containers:

![grafik](https://user-images.githubusercontent.com/827205/227547853-d5f5c639-4a34-4ff9-9221-d34266db9764.png)

**Comment by DanielRuf** [comment]
`docker-compose up --no-recreate` yields the following:

```
Attaching to iio-ic-react-http_1
iio-ic-react-http_1  | 
iio-ic-react-http_1  | 
iio-ic-react-http_1  | Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.33. in /app/vendor/composer/platform_check.php on line 24
iio-ic-react-http_1 exited with code 255
```

Looks like the docker-compose file is outdated:

![grafik](https://user-images.githubusercontent.com/827205/227550575-f0d900a0-ebbb-45cd-9e4d-3426076ecb1d.png)

**Comment by codeliner** [comment]
thx for bringing this up @DanielRuf . I'll look into it!

**Comment by codeliner** [comment]
changed all images to PHP 8.0 variant.
