### ISSUE TITLE
cody not executed

### ISSUE THREAD

**Issue by DanielRuf** [proophboard/php-cody-tutorial#2]
Similar to https://github.com/proophboard/node-cody-server/issues/1, cody does not do anything. But it runs locally as Docker container.

![grafik](https://user-images.githubusercontent.com/827205/227559890-4d247ef2-583a-4c28-9fec-6e60750a2d6b.png)

![grafik](https://user-images.githubusercontent.com/827205/227560189-6028592e-7d4d-46d6-87cc-3256621fc488.png)

**Comment by codeliner** [comment]
Indeed a bug in the free client! It has been fixed and you should be able to do the tutorial now. Sorry for the confusion and thank you for reporting!
